const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.JavaScriptInEvents.Folhagameplay_Event18_Act15,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.JavaScriptInEvents.Folhagameplay_Event29_Act7,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.JavaScriptInEvents.Folhagameplay_Event41_Act12,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.JavaScriptInEvents.Folhagameover_Event2_Act6,
		C3.JavaScriptInEvents.Folhagameover_Event3_Act6,
		C3.JavaScriptInEvents.Folhamenuprincipal_Event1_Act5,
		C3.JavaScriptInEvents.Folhatutorial_Event1_Act5
	];
};
self.C3_JsPropNameTable = [
	{Fixar: 0},
	{Piscar: 0},
	{playeranimation: 0},
	{Teclado: 0},
	{health: 0},
	{alive: 0},
	{invincible: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{player: 0},
	{PlayerAttackHItbox: 0},
	{lookingleft: 0},
	{invincibility: 0},
	{skeleton: 0},
	{enemypatrolpoint: 0},
	{chase: 0},
	{CampoDeVisão: 0},
	{MoverPara: 0},
	{imp: 0},
	{beholder: 0},
	{Projétil: 0},
	{DestruirExternamente: 0},
	{bullet: 0},
	{torch: 0},
	{Sólido: 0},
	{Mosaicof1: 0},
	{Interpolação: 0},
	{PlanoDeFundoEmBlocos: 0},
	{blood: 0},
	{swordhit: 0},
	{smokeskull: 0},
	{exit: 0},
	{maintitlebg: 0},
	{startbutton: 0},
	{instructionsbutton: 0},
	{titlelogo: 0},
	{tuturialbg: 0},
	{walktuto: 0},
	{jumptuto: 0},
	{attacktuto: 0},
	{playeranimationtutorial: 0},
	{playeranimationtutorial2: 0},
	{backbutton: 0},
	{Mouse: 0},
	{Áudio: 0},
	{heal: 0},
	{damagebox: 0},
	{gameover: 0},
	{continue: 0},
	{backtomainmenu: 0},
	{fadein: 0},
	{spark: 0},
	{button: 0},
	{button2: 0},
	{Âncora: 0},
	{lifecounter: 0},
	{imghistoria: 0},
	{textohistoria: 0},
	{pularhistoria: 0},
	{acento: 0},
	{finatexto: 0},
	{voltar: 0},
	{fase: 0}
];

self.InstanceType = {
	playeranimation: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	PlayerAttackHItbox: class extends self.ISpriteInstance {},
	skeleton: class extends self.ISpriteInstance {},
	enemypatrolpoint: class extends self.ISpriteInstance {},
	imp: class extends self.ISpriteInstance {},
	beholder: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	torch: class extends self.ISpriteInstance {},
	Mosaicof1: class extends self.ITilemapInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	blood: class extends self.ISpriteInstance {},
	swordhit: class extends self.ISpriteInstance {},
	smokeskull: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	maintitlebg: class extends self.ITiledBackgroundInstance {},
	startbutton: class extends self.ISpriteFontInstance {},
	instructionsbutton: class extends self.ISpriteFontInstance {},
	titlelogo: class extends self.ISpriteInstance {},
	tuturialbg: class extends self.ITiledBackgroundInstance {},
	walktuto: class extends self.ISpriteFontInstance {},
	jumptuto: class extends self.ISpriteFontInstance {},
	attacktuto: class extends self.ISpriteFontInstance {},
	playeranimationtutorial: class extends self.ISpriteInstance {},
	playeranimationtutorial2: class extends self.ISpriteInstance {},
	backbutton: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	heal: class extends self.ISpriteInstance {},
	damagebox: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteFontInstance {},
	continue: class extends self.ISpriteFontInstance {},
	backtomainmenu: class extends self.ISpriteFontInstance {},
	fadein: class extends self.ISpriteInstance {},
	spark: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	button2: class extends self.ISpriteInstance {},
	lifecounter: class extends self.ISpriteInstance {},
	imghistoria: class extends self.ISpriteInstance {},
	textohistoria: class extends self.ISpriteFontInstance {},
	pularhistoria: class extends self.ISpriteFontInstance {},
	acento: class extends self.ISpriteInstance {},
	finatexto: class extends self.ISpriteFontInstance {},
	voltar: class extends self.ISpriteFontInstance {}
}